#!/bin/bash

set -e

GPADMIN=gpadmin
GPVER=6
GPHOME=/opt/greenplum-db

if [ "$1" = configure ]; then

  chown -R ${GPADMIN}:${GPADMIN} ${GPHOME}-${GPVER}

  chmod -R -x+W ${GPHOME}-${GPVER}

  /sbin/ldconfig
fi
