#!/bin/bash

set -e

GPADMIN=gpadmin
GPHOME=/opt/cloudberry-db

if [ "$1" = configure ]; then

  chown -R ${GPADMIN}:${GPADMIN} ${GPHOME}

  cat << _EOF_ > /etc/ld.so.conf.d/cbdb.conf
${GPHOME}-${GPVER}/lib/
_EOF_

  /sbin/ldconfig
fi
