#!/bin/bash

set -e

OWNER=root
PXFHOME=/opt/greenplum-pxf-cb
GPHOME=/opt/greenplum-db-cb

chown -R ${OWNER}:${OWNER} ${PXFHOME}
chown    ${OWNER}:${OWNER} ${GPHOME}/lib/postgresql/pxf.so
chown    ${OWNER}:${OWNER} ${GPHOME}/share/postgresql/extension/pxf*

echo -en '\ntrusted = true' >> ${GPHOME}/share/postgresql/extension/pxf.control
