#!/bin/bash

set -e

GPADMIN=gpadmin
PXFVER=5
PXFHOME=/opt/greenplum-pxf-${PXFVER}
GPHOME=/opt/greenplum-db-6

if [ "$1" = configure ]; then

  chown -R ${GPADMIN}:${GPADMIN} ${PXFHOME}
  chown -R ${GPADMIN}:${GPADMIN} ${GPHOME}

fi
