#!/bin/bash

set -e

GPADMIN=gpadmin
PXFVER=6
PXFHOME=/opt/greenplum-pxf-${PXFVER}
GPHOME=/opt/greenplum-db-6

chown -R ${GPADMIN}:${GPADMIN} ${PXFHOME}
chown -R ${GPADMIN}:${GPADMIN} ${GPHOME}

echo 'trusted = true' >> ${GPHOME}/share/postgresql/extension/pxf.control
